# Top-level configuration

# Although we don't generally use this, it means KV commands use this as a prefix.
name = "report-listings"

[env.preview.vars]
VITE_SENTRY_ENV = "beta"
VITE_SENTRY_TRACES_SAMPLE_RATE = "1.0"

[env.production.vars]
VITE_SENTRY_ENV = "prod"
VITE_SENTRY_TRACES_SAMPLE_RATE = "1.0"
