name = "report-listings"
pages_build_output_dir = "dist"
compatibility_date = "2023-09-18"
compatibility_flags = ["nodejs_als", "nodejs_compat"]

[env.preview.vars]
LTI_AUD = "122010000000000***"
LTI_ISS = "https://lti-dev.canvas.ox.ac.uk"
SENTRY_ENV = "beta"
SENTRY_DSN = "https://d94d964a9faa42ee11afa535075bfa2d@o419652.ingest.us.sentry.io/4509441351483392"
SENTRY_TRACES_SAMPLE_RATE = "1.0"
VITE_SENTRY_ENV = "beta"
VITE_SENTRY_DSN = "https://d94d964a9faa42ee11afa535075bfa2d@o419652.ingest.us.sentry.io/4509441351483392"


[env.production.vars]
LTI_AUD = "122010000000000***"
LTI_ISS = "https://lti.canvas.ox.ac.uk"
SENTRY_ENV = "prod"
SENTRY_DSN = "https://d94d964a9faa42ee11afa535075bfa2d@o419652.ingest.us.sentry.io/4509441351483392"
SENTRY_TRACES_SAMPLE_RATE = "1.0"
VITE_SENTRY_ENV = "prod"
VITE_SENTRY_DSN = "https://d94d964a9faa42ee11afa535075bfa2d@o419652.ingest.us.sentry.io/4509441351483392"

